version: '3.7'

services:
  go.dating.fi.lading.page.frontend:
    image: edwardpm1206/go-dating-fi-landing-page-frontend:latest
    container_name: landing-page-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile.development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PORT}:3000
    expose:
      - '3000'
    env_file:
      - .env.development
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_STAGE=${REACT_APP_STAGE}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
