version: '3.7'

services:
  go.dating.fi.lading.page.frontend:
    image: edwardpm1206/go-dating-fi-landing-page-frontend:latest
    container_name: landing-page-frontend
    build:
      context: .
      dockerfile: .docker/Dockerfile.development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    env_file:
      - .env.development
    tty: true
    stdin_open: true
